name: CI Pipeline (Production)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  DAGSHUB_USERNAME: ${{ secrets.DAGSHUB_USERNAME }}
  DAGSHUB_TOKEN: ${{ secrets.DAGSHUB_TOKEN }}
  DOCKER_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

  MLFLOW_TRACKING_URI: https://dagshub.com/${{ secrets.DAGSHUB_USERNAME }}/Eksperimen_SML_Khatama.mlflow

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Check Env
        run: |
          echo "Checking Environment Variables..."
          python --version
          pip --version
          echo "MLFLOW URI: $MLFLOW_TRACKING_URI"

      - name: Install dependencies
        run: |
          pip install mlflow==2.19.0 dagshub pandas scikit-learn matplotlib seaborn virtualenv

      - name: Run mlflow project
        run: |
          # Jalankan training. Pastikan modelling.py ada di root repo baru!
          python ../../MLProject/modelling.py

      - name: Get latest MLflow run_id
        id: get_run_id
        run: |
          # Mengambil Run ID terakhir dari DagsHub
          RUN_ID=$(python -c "import mlflow; mlflow.set_tracking_uri('${{ env.MLFLOW_TRACKING_URI }}'); print(mlflow.search_runs(experiment_names=['Water_Quality_Basic'], order_by=['start_time DESC'], max_results=1).iloc[0].run_id)")
          echo "Run ID Found: $RUN_ID"
          echo "run_id=$RUN_ID" >> $GITHUB_OUTPUT

      - name: Download Model & Upload to GitHub Artifacts
        run: |
          # Kita download dulu modelnya dari DagsHub biar bisa di-upload ke GitHub Artifacts
          mlflow artifacts download --run-id ${{ steps.get_run_id.outputs.run_id }} --artifact-path model --dst-path ./downloaded_model
        
      - name: Upload to GitHub Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: trained-model
          path: ./downloaded_model

      - name: Build Docker Model
        run: |
          # Build image dengan nama temporary dulu
          mlflow models build-docker \
            --model-uri "runs:/${{ steps.get_run_id.outputs.run_id }}/model" \
            --name "water-quality-local:latest"

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Tag Docker Image
        run: |
          docker tag water-quality-local:latest ${{ secrets.DOCKER_HUB_USERNAME }}/water-quality-model:latest

      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/water-quality-model:latest
